export const CHANGE_FILM_GENRE = `CHANGE_FILM_GENRE`;
export const INCREMENT_FILM_COUNTER = `INCREMENT_FILM_COUNTER`;
export const LOAD_ALL_FILMS = `LOAD_ALL_FILMS`;
export const LOAD_PROMO_FILM = `LOAD_PROMO_FILM`;
export const LOAD_FILM_REVIEWS = `LOAD_FILM_REVIEWS`;
export const CHANGE_FAVORITE_STATUS = `CHANGE_FAVORITE_STATUS`;
export const ADD_REVIEW = `ADD_REVIEW`;
