export const REQUIRED_AUTHORIZATION = `REQUIRED_AUTHORIZATION`;
export const LOAD_USER_INFO = `LOAD_USER_INFO`;
export const LOAD_FAVORITES_FILMS = `LOAD_FAVORITES_FILMS`;
export const ADD_TO_FAVORITES = `ADD_TO_FAVORITES`;
export const DELETE_FROM_FAVORITES = `DELETE_FROM_FAVORITES`;
